TIPOS_ID = ['DNI', 'CUIL', 'CUIT']
FINALIDADES = ['Eventos/capacitaciones', 'Co-Working']
HORA_APERTURA = 8
HORA_CIERRE = 23
FRANJAS_HORARIAS = (HORA_APERTURA..(HORA_CIERRE-1)).map { |p| [p, p+1] }
MAX_OCUPACIONES = 30
